### ISSUE TITLE
Profile spec A1: Why specify unicode normalization?

### ISSUE THREAD

**Issue by xrotwang** [unicode-cookbook/cookbook#30]
It's not clear to me, why the type of unicode normalization of the text in the orthography profile needs to be specified. At least in the `segments` package, the data is normalized using NFD upon reading the profile anyway. So isn't this merely an implementation detail of the profile processor?

**Comment by bambooforest** [comment]
We state: A profile is a Unicode UTF-8 normalized following NFC (or NFD if specified in the metadata) that includes the information pertinent to the orthography.

I saw this is beneficial for the OP's creation, i.e. it puts the onus on the OP creator to have a consistent normalization throughout the OP (instead of saying being mixed NFC and NFD characters). In this sense the OP would be "valid" before it goes to any processing tools. If it's never processed by `segments` or some other tool, it would still be consistent in its normalization form.

But maybe this isn't a good argument for the profile specification?

**Comment by xrotwang** [comment]
Hm. Considering that
- it's easy to go from one normalization to the other and back
- a meaningful mix of normalizations in the same text doesn't exist (right?)

I'd say we can leave this unspecified; i.e. we allow for easier authoring (no onus at all!) because processing apps will do the appropriate and consistent normalization anyway.

The only problem I'd see with this approach is that simple validation, e.g. checking if all graphemes in a profile are unique, would already fall under "processing app", i.e. would have to do normalization - and in case of uniqueness errors, the simplification in terms of authoring would shoot the author in the foot as difficult debugging.

**Comment by HughP** [comment]
FWIW: as a software user coming to this issue: having a flag to set on `segments` (python code) defining how I want the software to behave, regardless of how my data is encoded makes sense. There might be a use case for having a default, and then two flags.
While NFC and NFD are canonically equivalent there are orthographies where it would _appear_ that both are used at the same time. I say appear, because some combinations do not ever break down into components.  In the orthography that I am working with this week, we have several characters which are composite characters `U+00F6 ö LATIN SMALL LETTER O WITH DIAERESIS` and this is the NFC form, however, there is no NFC form for `U+028B+U+0308 ʋ̈ LATIN SMALL LETTER V WITH HOOK with COMBINING DIAERESIS` which is also in the orthography. If we want a count of DIAERESIS, we have to process it as NFD, even if the orthography default encoding is NFC.

**Comment by bambooforest** [comment]
Precisely, @HughP. Thanks! In 5.8 (Missing decomposition) we suggest not using precomposed  e.g. vowels and rhotic hooks for schwa and reversed e because they are the only two with "precomposed" forms and they do not decompose.

So I imagine a situation where I create an OP with decomposed <a˞, ə˞>, but the input data is a mix of decomposed <a˞> (there's no precomposed character) and precomposed <ə˞>, which does not decompose. (This could be because different people worked on the same data.) So a mix of normalizations can exist, but it's not necessarily meaningful. :) Precomposing the OP or decomposing the input will not match <ə˞> and <ɚ>. For the segmentation to work, the programmer has to change one of the two.

**Comment by xrotwang** [comment]
Yes. To me this sounds like an issue you'd have to deal with in a preprocessing step, similar to dealing with [UNICODE confusables](https://unicode.org/cldr/utility/confusables.jsp). (Although this preprocessing could use orthography profiles internally, as for example in our [multicode package](https://github.com/cldf/multicode).)

**Comment by bambooforest** [comment]
Then I will have to make this clearer in the specifications / processing. Btw @xrotwang the link doesn't work at http://multicode.digling.org

**Comment by bambooforest** [comment]
I've removed the NFC/NFD specification in A1 and updated B7.
