### ISSUE TITLE
Profile spec B1: Whether a profile column contains regex or not should be specified in profile metadata

### ISSUE THREAD

**Issue by xrotwang** [unicode-cookbook/cookbook#33]
Somewhat the opposite case to #31 appears in B1: Here it is stated that
> applications ... can also offer to interpret a profile in the literal sense

I think there isn't really a choice here: If the content of the profile is regular expressions, it must be processed as such and vice versa. Thus the content type of columns in the profile must be known to the processor, and therefore specified in the profile metadata.

**Comment by bambooforest** [comment]
Also:

93, B1: "Each line of a profile will be interpreted as a regular expression."  Conflicts with A4, "the metadata file should provide information about the orthography profile’s structure and contents, including... whether they should be processed as regular expressions"

**Comment by bambooforest** [comment]
@xrotwang so instead of:

```B1. Each line of a profile will be interpreted as a regular expression. Software applications using profiles can also offer to interpret a profile in the literal sense to avoid the necessity for the user to escape regular expression metacharacters in the profile. However, this is only possible when no contexts or classes are described, so this seems only useful in the most basic orthographies.```

Something like:

B1. Each line of a profile will be interpreted according to content type of the column specified in the profile metadata. Content types include literal and regular expression.

**Comment by xrotwang** [comment]
Yes, that sounds about right.

**Comment by HughP** [comment]
@bambooforest I forget, in the book did you mention which "dialect" of regex you are invoking? i.e. perl, https://en.wikipedia.org/wiki/Comparison_of_regular_expression_engines

**Comment by xrotwang** [comment]
AFAIR no specific regex dialect is mentioned - and that's possibly problematic. It does sound as if look-ahead and look-behind must be supported by the dialect - which already rules out the better specified, more minimal regex variants.

**Comment by bambooforest** [comment]
@HughP no we didn't specify. Do you guys @xrotwang think we should do this in the metadata or leave it again up to the user / processor?

**Comment by xrotwang** [comment]
I think there is no such thing as a regex standard; thus, it's already up to the processor. When you are using regexes in your orthography profile, you basically tie yourself to one particular processor.

**Comment by HughP** [comment]
@bambooforest  here is a nice article with a diagram showing which elements of RegEx are supported across Perl, Python, and EMacs. https://www.johndcook.com/blog/regex-perl-python-emacs/ I only offer this as a good visual difference between options in RegEx engines.

Personally, in my use of RegEx I like working with Perl RegEx and natural language data, because one can utilize the [Unicode properties of characters in the RegEx](https://perldoc.perl.org/perlunicode.html#Unicode-Character-Properties). POSIX character classes don't work for non-ASCII characters.  One can even target things like `script`.

As I understand it Python generally has two RegEx engine options with variations `re` and [`regex`](https://pypi.org/project/regex/) are the two modules I know about. 

Oniguruma seems to be an inserting engine enabling Perl like syntax and [ponyguruma](https://github.com/mitsuhiko/ponyguruma/ 
) brings that to Python. 

@xrotwang Because RegExs are allowed in the orthography profile, I would assume that the software to process the RegEx would then ship with Segments (or segments and the processor would ship together as part of a meta-package. That is Segments is the orthography profile processor right?

**Comment by xrotwang** [comment]
Yes, `segments` is an orthography profile processor. The only regex implementation it "ships with", though, is the `regex` package. `segments` doesn't support the left- and right-context columns from the orthography profile spec, though.
